apiVersion: v1
kind: Pod
spec:
  containers:
    - name: git
      image: alpine/git:2.45.2
      command: ["sleep"]
      args: ["infinity"]
      
    - name: shell
      image: ubuntu
      command: ["sleep"]
      args: ["infinity"]

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["/busybox/sleep"]
      args: ["infinity"]
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        # - name: docker-config
        #   mountPath: /kaniko/.docker
      tty: true

  volumes:
    - name: workspace
      emptyDir: {}

    # - name: docker-config
    #   secret:
    #     secretName: niyov-harbor-registry-secret
